[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://실제-백엔드-URL.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://실제-백엔드-URL.onrender.com" 